import type { Product, Category, InventoryTransaction } from '../types/inventory';

export const initialCategories: Category[] = [
  {
    id: 'cat-dt',
    name: 'Điện thoại & Máy tính bảng',
    description: 'Điện thoại thông minh, máy tính bảng, iPad, phụ kiện di động',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    syncStatus: 'synced',
    isDeleted: false,
  },
  {
    id: 'cat-lt',
    name: 'Laptop & Máy tính',
    description: 'Laptop văn phòng, laptop gaming, máy tính để bàn, linh kiện PC',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    syncStatus: 'synced',
    isDeleted: false,
  },
  {
    id: 'cat-pk',
    name: 'Phụ kiện & Linh kiện',
    description: 'Cáp sạc, tai nghe, pin dự phòng, chuột, bàn phím',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    syncStatus: 'synced',
    isDeleted: false,
  },
  {
    id: 'cat-tb',
    name: 'Thiết bị Gia dụng',
    description: 'Tủ lạnh, máy giặt, nồi cơm điện, quạt máy, lò vi sóng',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    syncStatus: 'synced',
    isDeleted: false,
  },
  {
    id: 'cat-tt',
    name: 'Thời trang & May mặc',
    description: 'Quần áo nam nữ, giày dép, túi xách, phụ kiện thời trang',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    syncStatus: 'synced',
    isDeleted: false,
  },
  {
    id: 'cat-mp',
    name: 'Mỹ phẩm & Chăm sóc cá nhân',
    description: 'Son môi, kem dưỡng, dầu gội, sữa tắm, nước hoa',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    syncStatus: 'synced',
    isDeleted: false,
  },
  {
    id: 'cat-tp',
    name: 'Thực phẩm & Đồ uống',
    description: 'Bánh kẹo, đồ đóng hộp, nước giải khát, cà phê, trà',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    syncStatus: 'synced',
    isDeleted: false,
  },
  {
    id: 'cat-mb',
    name: 'Đồ dùng Mẹ & Bé',
    description: 'Sữa, tã bỉm, đồ chơi trẻ em, xe đẩy, bình sữa',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    syncStatus: 'synced',
    isDeleted: false,
  },
  {
    id: 'cat-vp',
    name: 'Văn phòng phẩm & Sách',
    description: 'Giấy in, bút, sổ tay, sách tham khảo, dụng cụ học tập',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    syncStatus: 'synced',
    isDeleted: false,
  },
  {
    id: 'cat-ns',
    name: 'Nông sản & Thực phẩm tươi',
    description: 'Rau củ quả tươi, thịt cá, hải sản, hoa quả nhập khẩu',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    syncStatus: 'synced',
    isDeleted: false,
  },
  {
    id: 'cat-dc',
    name: 'Dụng cụ & Thể thao',
    description: 'Đồ tập gym, bóng đá, cầu lông, lều dã ngoại, phụ kiện thể thao',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    syncStatus: 'synced',
    isDeleted: false,
  },
  {
    id: 'cat-nc',
    name: 'Nhà cửa & Đời sống',
    description: 'Đồ dùng nhà bếp, chăn ga gối nệm, trang trí nội thất',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    syncStatus: 'synced',
    isDeleted: false,
  },
];

export const initialProducts: Product[] = [];
export const initialTransactions: InventoryTransaction[] = [];

